import jsPDF from 'jspdf';

// Escape a single CSV field: quote it if it contains a comma/quote/newline, and
// neutralize leading =,+,-,@ so opening the file in Excel/Sheets can't trigger
// formula execution (CSV/formula injection).
const csvField = (value) => {
  let str = String(value ?? '');
  if (/^[=+\-@]/.test(str)) {
    str = `'${str}`;
  }
  if (/[",\n]/.test(str)) {
    str = `"${str.replace(/"/g, '""')}"`;
  }
  return str;
};

// Export data to CSV
export const exportToCSV = (data, filename = 'AST_Results.csv') => {
  if (!data || data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = ['Date', 'Patient ID', 'Age', 'Sex', 'Ward', 'Specimen', 'Organism', 'Antibiotic', 'Zone (mm)', 'Interpretation'];
  const csvRows = [];

  // Add headers
  csvRows.push(headers.map(csvField).join(','));

  // Add data rows
  data.forEach(row => {
    const values = [
      row.date || '',
      row.patientId || '',
      row.age || '',
      row.sex || '',
      row.ward || '',
      row.specimen || '',
      row.organism || '',
      row.antibiotic || '',
      row.zone || '',
      row.interpretation || ''
    ];
    csvRows.push(values.map(csvField).join(','));
  });

  // Create and download blob
  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  window.URL.revokeObjectURL(url);
};

// Export to PDF (antibiogram report)
export const exportAntibiogramPDF = (antibiogramData, facilityName = 'LabAST Lab') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(18);
  doc.text('Antibiogram Report', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(facilityName, pageWidth / 2, 30, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 38, { align: 'center' });
  
  // Table headers
  doc.setFontSize(10);
  const startY = 50;
  let y = startY;
  
  // Header row
  doc.setFillColor(230, 230, 230);
  doc.rect(20, y - 5, 170, 10, 'F');
  doc.text('Organism', 25, y + 2);
  doc.text('Antibiotic', 80, y + 2);
  doc.text('% Susceptible', 140, y + 2);
  
  y += 12;
  
  // Data rows
  let rowCount = 0;
  for (const [key, value] of Object.entries(antibiogramData)) {
    if (rowCount > 0 && rowCount % 20 === 0) {
      doc.addPage();
      y = 20;
    }
    
    // Alternating row background
    if (rowCount % 2 === 0) {
      doc.setFillColor(245, 245, 245);
      doc.rect(20, y - 4, 170, 8, 'F');
    }
    
    doc.text(key.split('_')[0] || key, 25, y + 2);
    doc.text(key.split('_')[1] || '', 80, y + 2);
    doc.text(`${value.percentage}% (n=${value.total})`, 140, y + 2);
    
    y += 10;
    rowCount++;
  }
  
  // Footer
  doc.setFontSize(8);
  doc.text('For reference only — verify against your current CLSI/EUCAST breakpoint tables.', pageWidth / 2, doc.internal.pageSize.getHeight() - 16, { align: 'center' });
  doc.text('Generated by LabAST Pro - Offline AST Dashboard', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  
  doc.save('Antibiogram_Report.pdf');
};
